# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20151126_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
