# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0008_subscribers_category'),
        ('pages', '0003_auto_20160201_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ManyToManyField(to='micro_blog.Category'),
        ),
    ]
