# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20160422_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
