# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20160423_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
