# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_page_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
