# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20160428_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_info',
        ),
        migrations.DeleteModel(
            name='simplecontact',
        ),
    ]
