# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0016_country'),
        ('pages', '0010_auto_20160511_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micro_blog.Country'),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
    ]
