# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20170301_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
