# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0017_country_slug'),
        ('pages', '0015_auto_20170307_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micro_blog.Country'),
        ),
    ]
