# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 11:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_menu_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='contact_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
