# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0003_post_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_on',
            field=models.DateField(default=datetime.datetime(2015, 12, 14, 10, 43, 23, 648809)),
            preserve_default=False,
        ),
    ]
