# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0004_post_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
