# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0006_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='blog_post',
            field=models.BooleanField(default=True),
        ),
    ]
