# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0007_auto_20160118_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='micro_blog.Category'),
        ),
    ]
