# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0008_subscribers_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[(b'D', b'Draft'), (b'P', b'Published'), (b'T', b'Rejected'), (b'R', b'Review')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
