# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0009_auto_20160212_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='old_slugs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
