# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0011_post_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
