# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0012_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_slugs',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
