# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0014_auto_20160422_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='', max_length=500),
        ),
    ]
