# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0015_post_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_description',
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='', max_length=500),
        ),
    ]
