# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0017_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_published_blogs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='min_published_blogs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
