# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog', '0018_auto_20171003_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='micro_blog.Category'),
        ),
    ]
