# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 13:38
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name=b'email address')),
                ('user_roles', models.CharField(choices=[(b'Admin', b'Admin'), (b'PM', b'Project Manager'), (b'Designer', b'Designer'), (b'Developer', b'Developer')], max_length=10)),
                ('date_of_birth', models.DateField(default=b'1970-01-01')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_special', models.BooleanField(default=False)),
                ('first_name', models.CharField(default=b'', max_length=100)),
                ('last_name', models.CharField(default=b'', max_length=100)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=10)),
                ('fb_profile', models.URLField(default=b'')),
                ('tw_profile', models.URLField(default=b'')),
                ('ln_profile', models.URLField(default=b'')),
                ('google_plus_url', models.URLField(default=b'')),
                ('about', models.CharField(blank=True, default=b'', max_length=2000, null=True)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=150)),
                ('address', models.TextField(default=b'', max_length=1000)),
                ('mobile', models.BigIntegerField(default=b'0')),
                ('website', models.URLField(default=b'', null=True)),
                ('phones', models.TextField(default=b'', max_length=100, null=True)),
                ('pincode', models.TextField(default=b'', max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('blog_moderator', 'Can enable or disable blog posts'), ('blogger', 'Can write blog posts')),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('experience', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('featured_image', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_opening', models.IntegerField(default=True)),
                ('posted_on', models.DateField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField(default=b'')),
            ],
        ),
    ]
