# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0002_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_published_blogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='min_published_blogs',
            field=models.IntegerField(default=0),
        ),
    ]
